# Generated by Django 4.1.4 on 2022-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='original_cart',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=100),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
