# Generated by Django 4.1.4 on 2022-12-15 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
        ('checkout', '0003_alter_ticketorder_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='userprofiles.userprofile'),
        ),
    ]
