# Generated by Django 4.1.4 on 2022-12-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_ticketorder_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='ticket_days',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
