# Generated by Django 4.1.4 on 2022-12-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_hotel_nights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='hotel_nights',
            new_name='has_length',
        ),
    ]
