# Generated by Django 4.1.4 on 2022-12-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Ticket',
        ),
    ]
