# Generated by Django 4.1.4 on 2022-12-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_hotel_nights_ticket_has_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='has_length',
            new_name='has_days',
        ),
    ]
