# Generated by Django 4.1.4 on 2022-12-15 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dates',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
